import { createReducer } from "@reduxjs/toolkit";
import comidasActions from "../actions/comidasActions";

const initialState = {
    comidas: [
        {
            "_id": "65654b4b950b314069e90ab0",
            "nombre": "Bife de Res a la Parrilla",
            "descripcion": "Un jugoso bife de res a la parrilla condimentado con hierbas frescas y acompañado de papas asadas y espárragos tiernos.",
            "precio": 5899,
            "estrellas": 80,
            "vegano": false,
            "categoria": "carnes",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Bife%20de%20Res%20a%20la%20Parrilla-min.png",
            "enCarrito": false,
            "rating": "4.5",
            "vendidos": 100,
            "descripcionDetallada": "Prepárate para disfrutar de un exquisito bife de res a la parrilla, cocinado a la perfección para obtener ese punto jugoso y lleno de sabor que tanto te gusta. Nuestros chefs expertos sazonan la carne con una selección de hierbas frescas que realzan su sabor único. Acompañamos este delicioso plato con papas asadas, crocantes por fuera y tiernas por dentro, además de espárragos frescos que aportan un toque de elegancia. Una experiencia culinaria que deleitará tu paladar y te dejará con ganas de más.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab1",
            "nombre": "Lasagna Clásica",
            "descripcion": "Nuestra lasagna casera con capas de pasta al huevo, ricota cremosa, carne molida y salsa de tomate, gratinada con queso mozzarella derretido.",
            "precio": 4321,
            "estrellas": 95,
            "vegano": false,
            "categoria": "pastas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Lasagna%20Clasica-min.png",
            "enCarrito": false,
            "rating": "4.2",
            "vendidos": 90,
            "descripcionDetallada": "Déjate conquistar por nuestra Lasagna Clásica, una obra maestra de la cocina italiana. Capa tras capa de pasta al huevo cocinada a la perfección, se intercalan con ricota cremosa y una sabrosa mezcla de carne molida sazonada con especias secretas. Todo esto es coronado con nuestra salsa de tomate casera, que aporta ese toque de acidez y frescura. Para rematar, gratinamos la lasagna con generosas porciones de queso mozzarella, logrando un dorado irresistible. Cada bocado es una explosión de sabores que te transportará a las cocinas de la bella Italia.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab4",
            "nombre": "Sopa de Champiñones",
            "descripcion": "Una sopa cremosa de champiñones frescos, cocida a fuego lento con cebolla caramelizada y ajo, coronada con cebollín picado.",
            "precio": 2499,
            "estrellas": 250,
            "vegano": true,
            "categoria": "sopas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Sopa%20de%20Champi%C3%B1ones-min.png",
            "enCarrito": false,
            "rating": "4.7",
            "vendidos": 80,
            "descripcionDetallada": "Sumérgete en el reconfortante abrazo de nuestra Sopa de Champiñones, una deliciosa mezcla de sabores y texturas. Utilizamos champiñones frescos, cocidos a fuego lento con cebolla caramelizada y ajo, para crear una base rica y cremosa. La mezcla de aromas es simplemente irresistible. Para rematar, coronamos la sopa con cebollín picado, que aporta un toque fresco y vibrante. Cada cucharada es una experiencia reconfortante que te hará volver por más.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab5",
            "nombre": "Sushi de Salmón y Palta",
            "descripcion": "Finas rebanadas de salmón fresco y palta cremosa envueltas en alga nori y arroz sazonado, acompañadas de salsa de soya y wasabi.",
            "precio": 3899,
            "estrellas": 142,
            "vegano": false,
            "categoria": "sushi",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Sushi%20de%20Salmon%20y%20Palta-min.png",
            "enCarrito": false,
            "rating": "4.6",
            "vendidos": 110,
            "descripcionDetallada": "Nuestro Sushi de Salmón y Palta es una oda a la frescura y la armonía de sabores. Finas rebanadas de salmón fresco se combinan con la cremosidad de la palta, envueltas en alga nori y arroz sazonado con maestría. Cada bocado es una explosión de texturas y sabores que te transportará a las costas del Pacífico. Acompañamos este festín con salsa de soya para un toque salado y wasabi para un toque picante. Prepárate para una experiencia culinaria inolvidable.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab6",
            "nombre": "Tarta de Manzana",
            "descripcion": "Una deliciosa tarta de manzana con una base de masa hojaldrada y relleno de manzanas caramelizadas, espolvoreada con canela y azúcar glas.",
            "precio": 3199,
            "estrellas": 111,
            "vegano": true,
            "categoria": "dulces",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Tarta%20de%20Manzana-min.png",
            "enCarrito": false,
            "rating": "4.4",
            "vendidos": 130,
            "descripcionDetallada": "Nuestra Tarta de Manzana es un homenaje a la clásica y reconfortante combinación de manzanas y canela. La base de masa hojaldrada, crujiente y dorada, sirve como lecho para un relleno generoso de manzanas caramelizadas, tiernas y llenas de sabor. Para rematar, espolvoreamos con canela y azúcar glas, creando una capa de dulzura y aroma irresistibles. Cada bocado es un deleite para los sentidos, una experiencia que evoca los sabores de la infancia y te deja con una sensación de satisfacción plena.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab7",
            "nombre": "Fideos con Albóndigas",
            "descripcion": "Fideos al dente servidos con albóndigas jugosas y salsa de tomate casera, espolvoreados con queso parmesano rallado.",
            "precio": 3452,
            "estrellas": 147,
            "vegano": false,
            "categoria": "pastas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Fideos%20con%20Albondigas-min.png",
            "enCarrito": false,
            "rating": "4.1",
            "vendidos": 100,
            "descripcionDetallada": "Prepárate para disfrutar de una experiencia reconfortante con nuestros Fideos con Albóndigas. Los fideos al dente se combinan con albóndigas jugosas y una salsa de tomate casera, cocinada a fuego lento para obtener ese sabor auténtico. Para rematar, espolvoreamos con generosas cantidades de queso parmesano rallado, que se derrite sobre la pasta creando una capa de sabor irresistible. Cada bocado es una explosión de sabores que te dejará con una sensación de plenitud y satisfacción.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab9",
            "nombre": "Pizza Vegana de Verduras",
            "descripcion": "Una deliciosa pizza vegana con una mezcla de champiñones, pimientos, cebolla y aceitunas negras, cubierta con queso vegano derretido.",
            "precio": 3699,
            "estrellas": 135,
            "vegano": true,
            "categoria": "pizzas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Pizza%20Vegana-min.png",
            "enCarrito": false,
            "rating": "4.3",
            "vendidos": 90,
            "descripcionDetallada": "Nuestra Pizza Vegana de Verduras es un festín de colores y sabores que deleitará hasta a los paladares más exigentes. La base de masa crujiente sirve como lienzo para una generosa mezcla de champiñones, pimientos, cebolla y aceitunas negras, que aportan una explosión de sabores y texturas. Pero la estrella de esta pizza es el queso vegano derretido, que completa esta experiencia culinaria con su cremosidad irresistible. Prepárate para un viaje de sabores sin igual.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab8",
            "nombre": "Hamburguesa Vegetariana",
            "descripcion": "Una sabrosa hamburguesa vegetariana a base de garbanzos, acompañada de lechuga fresca, tomate y mayonesa vegana, servida en pan integral.",
            "precio": 3125,
            "estrellas": 123,
            "vegano": true,
            "categoria": "hamburguesas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Hamburguesa%20Vegetariana-min.png",
            "enCarrito": false,
            "rating": "4.2",
            "vendidos": 70,
            "descripcionDetallada": "Nuestra Hamburguesa Vegetariana es una explosión de sabores y texturas para satisfacer hasta el paladar más exigente. Está elaborada a base de garbanzos, cuidadosamente seleccionados y sazonados para obtener una mezcla sabrosa y nutritiva. La hamburguesa se complementa con lechuga fresca y tomate, que aportan un contraste crujiente y refrescante. Para los amantes de lo vegano, la mayonesa utilizada es 100% vegana. Todo esto es servido en un suave pan integral que completa esta experiencia culinaria única.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90aba",
            "nombre": "Ensalada de Quinoa y Garbanzos",
            "descripcion": "Una ensalada nutritiva con quinoa cocida, garbanzos, pepino, tomate y aguacate, aliñada con vinagreta de limón y comino.",
            "precio": 2860,
            "estrellas": 210,
            "vegano": true,
            "categoria": "ensaladas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Ensalada%20de%20Quinoa%20y%20Garbanzos-min.png",
            "enCarrito": false,
            "rating": "4.4",
            "vendidos": 80,
            "descripcionDetallada": "Nuestra Ensalada de Quinoa y Garbanzos es mucho más que una simple ensalada, es una explosión de nutrientes y sabores que revitalizará tu paladar. La quinoa cocida se combina con garbanzos, pepino, tomate y aguacate, creando una mezcla equilibrada de texturas y sabores. Para realzar el conjunto, hemos preparado una vinagreta de limón y comino que aporta un toque cítrico y aromático. Cada bocado es una celebración de la frescura y la nutrición, una experiencia que te dejará con una sensación de bienestar.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90abb",
            "nombre": "Sopa de Tomate y Albahaca",
            "descripcion": "Una sopa reconfortante de tomate maduro y albahaca fresca, servida con croutons de pan y una pizca de queso parmesano.",
            "precio": 2550,
            "estrellas": 121,
            "vegano": true,
            "categoria": "sopas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Sopa%20de%20Tomate%20y%20Albahaca-min.png",
            "enCarrito": false,
            "rating": "4.5",
            "vendidos": 100,
            "descripcionDetallada": "Sumérgete en la reconfortante calidez de nuestra Sopa de Tomate y Albahaca, una combinación clásica que nunca pasa de moda. Utilizamos tomates maduros de la más alta calidad, cocidos a fuego lento para intensificar su sabor natural. La albahaca fresca añade un toque de frescura y aroma, elevando esta sopa a otro nivel. La experiencia se completa con croutons de pan crujientes y una pizca de queso parmesano, que aporta un toque salado y umami. Cada cucharada es un bocado de consuelo y satisfacción.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab3",
            "nombre": "Ensalada César",
            "descripcion": "Crujientes hojas de lechuga romana mezcladas con aderezo césar casero, croutons de ajo y lascas de queso parmesano.",
            "precio": 2899,
            "estrellas": 136,
            "vegano": false,
            "categoria": "ensaladas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Ensalada%20Cesar-min.png",
            "enCarrito": false,
            "rating": "4",
            "vendidos": 70,
            "descripcionDetallada": "Nuestra Ensalada César es una explosión de texturas y sabores que te transportará al corazón de la cocina mediterránea. Las crujientes hojas de lechuga romana se combinan a la perfección con nuestro aderezo césar casero, que aporta un equilibrio exquisito de notas ácidas y cremosas. Los croutons de ajo, crujientes por fuera y tiernos por dentro, aportan un contraste delicioso. Para coronar, generosas lascas de queso parmesano añaden un toque salado y umami. Cada bocado es una experiencia gastronómica que te dejará con una sonrisa en el rostro.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ab2",
            "nombre": "Pizza BBQ con Pollo",
            "descripcion": "Una pizza gourmet con salsa barbacoa, tierno pollo a la parrilla, cebolla morada y cilantro fresco, coronada con queso cheddar derretido.",
            "precio": 4599,
            "estrellas": 150,
            "vegano": false,
            "categoria": "pizzas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Pizza%20BBQ%20con%20Pollo-min.png",
            "enCarrito": false,
            "rating": "4.3",
            "vendidos": 120,
            "descripcionDetallada": "Nuestra Pizza BBQ con Pollo es un festín para los amantes de los sabores audaces. Comienza con una base de salsa barbacoa, rica y ligeramente ahumada, que sirve como lienzo para los ingredientes estrella. El pollo a la parrilla, jugoso y lleno de sabor, se combina con cebolla morada que aporta un toque picante y cilantro fresco que añade una nota herbácea. Pero la verdadera estrella es el queso cheddar derretido, que cubre la pizza con su cremosidad irresistible. Cada bocado es una explosión de sabores que te dejará anhelando el próximo.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90abe",
            "nombre": "Canelones de Carne",
            "descripcion": "Canelones rellenos de una mezcla de carne molida, espinacas y ricota, cubiertos con bechamel y gratinados con queso parmesano.",
            "precio": 3920,
            "estrellas": 145,
            "vegano": false,
            "categoria": "pastas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Canelones%20de%20Carne-min.png",
            "enCarrito": false,
            "rating": "4.2",
            "vendidos": 70,
            "descripcionDetallada": "Los Canelones de Carne son una opción reconfortante y sabrosa para los amantes de la pasta. Están rellenos de una mezcla deliciosa de carne molida, espinacas y ricota, que proporciona una combinación de sabores y texturas. Cubiertos con bechamel y gratinados con queso parmesano, ofrecen una capa dorada y cremosa que complementa perfectamente el relleno. Un plato clásico de la cocina italiana que nunca pasa de moda.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90abf",
            "nombre": "Tarta de Limón Vegana",
            "descripcion": "Una tarta refrescante de limón sin productos de origen animal, con una base de galleta y un relleno suave y ácido.",
            "precio": 3150,
            "estrellas": 254,
            "vegano": true,
            "categoria": "dulces",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Tarta%20de%20Lim%C3%B3n%20Vegana-min.png",
            "enCarrito": false,
            "rating": "4.3",
            "vendidos": 90,
            "descripcionDetallada": "Nuestra Tarta de Limón Vegana es una explosión de sabor cítrico y frescura en cada bocado. La base de galleta proporciona un contraste crujiente y dulce, complementando a la perfección el relleno suave y ácido de limón. Esta delicia no contiene productos de origen animal, lo que la hace apta para veganos. Cada porción es una experiencia refrescante y deliciosa que deleitará tu paladar.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ac0",
            "nombre": "Pechuga de Pollo a la Parrilla",
            "descripcion": "Jugosa pechuga de pollo marinada y cocinada a la parrilla, acompañada de puré de papas y espárragos al vapor.",
            "precio": 5499,
            "estrellas": 147,
            "vegano": false,
            "categoria": "carnes",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Pechuga%20de%20Pollo%20a%20la%20Parrilla-min.png",
            "enCarrito": false,
            "rating": "4.7",
            "vendidos": 140,
            "descripcionDetallada": "Nuestra Pechuga de Pollo a la Parrilla es una experiencia culinaria que combina jugosidad y sabor en cada bocado. La pechuga de pollo se marina cuidadosamente para realzar su sabor y se cocina a la parrilla para obtener ese característico aroma ahumado. Se sirve acompañada de un cremoso puré de papas y espárragos al vapor, creando un equilibrio perfecto entre sabores y texturas. Esta opción no es apta para veganos, pero es una delicia para los amantes de la carne.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ac1",
            "nombre": "Fettuccine Alfredo",
            "descripcion": "Fettuccine frescos bañados en una cremosa salsa Alfredo con manteca y parmesano, adornados con perejil picado.",
            "precio": 3890,
            "estrellas": 158,
            "vegano": false,
            "categoria": "pastas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Fettuccine%20Alfredo-min.png",
            "enCarrito": false,
            "rating": "4.6",
            "vendidos": 120,
            "descripcionDetallada": "Nuestros Fettuccine Alfredo son una oda a la indulgencia y la cremosidad. Los fettuccine frescos se bañan en una lujosa salsa Alfredo preparada con manteca y queso parmesano, creando una textura suave y sedosa que envuelve cada hebra de pasta. El plato se completa con perejil picado para un toque de frescura. Esta opción es una delicia para los amantes de los sabores ricos y reconfortantes.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ac2",
            "nombre": "Pizza Vegetariana",
            "descripcion": "Una colorida pizza con pimientos, champiñones, cebolla y aceitunas negras, cubierta con queso mozzarella derretido.",
            "precio": 4199,
            "estrellas": 169,
            "vegano": true,
            "categoria": "pizzas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Pizza%20Vegetariana-min.png",
            "enCarrito": false,
            "rating": "4.5",
            "vendidos": 130,
            "descripcionDetallada": "Nuestra Pizza Vegetariana es una explosión de colores y sabores frescos. Pimientos, champiñones, cebolla y aceitunas negras se combinan armoniosamente sobre una base de salsa de tomate, creando un festín visual y gustativo. La generosa capa de queso mozzarella derretido aporta cremosidad y un toque salado. Esta opción es apta para veganos y es una delicia para todos los amantes de la pizza.",
            "__v": 0
            },
            {
            "_id": "65654b4b950b314069e90ac3",
            "nombre": "Ensalada de Espinacas y Arándanos",
            "descripcion": "Espinacas frescas mezcladas con arándanos, nueces tostadas y queso feta, aliñadas con vinagreta de frambuesa.",
            "precio": 2999,
            "estrellas": 125,
            "vegano": false,
            "categoria": "ensaladas",
            "imgUrl": "https://raw.githubusercontent.com/nachof948/imagenes-ecommerce/main/Ensalada%20de%20Espinacas%20y%20Ar%C3%A1ndanos-min.png",
            "enCarrito": false,
            "rating": "4.4",
            "vendidos": 100,
            "descripcionDetallada": "Nuestra Ensalada de Espinacas y Arándanos es una combinación perfecta de frescura y sabor. Las espinacas frescas se mezclan con arándanos jugosos, nueces tostadas y queso feta para crear una sinfonía de texturas y sabores. La vinagreta de frambuesa aporta un toque agridulce que realza el conjunto. Cada bocado es una experiencia de sabor equilibrada y deliciosa.",
            "__v": 0
            }
    ]
}

const comidasReducer = createReducer( initialState, (builder)=>{
    builder
    .addCase(comidasActions.obtener_comidas, (state, action)=>{
        // console.log(action.payload);
        return console.log(action.payload)
    })
})

export default comidasReducer;